language: python
python:
- '3.6.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: heroku
  api_key:
    secure: fZ0PgMgq+6n5Yf3ooRzH8Iup0dHdxiWPZWawU5JgFmeXfzhC4a738cdemFl5PdZTlMvgUORr69FfA0MPx8/96W9Ukw9Rcd+asN5ui9s6yjhf6PQN9V45fg5fjfurWY/qOT3PwgtrpDgftIengheqFI5gIDWRKGt40Y/mmfJtXKMmqhx7rdjp8nUWPfYR+4aaPmCO7izWvOhfHq8oXtReHd5zQRvKQ/5LKrWdSuGoar+1HE9wXsVqiDO6Sil+ktlIffAhPEhvDqkKfnvoJj2mcJM6RFGAJlf3eBFNSScns0fgjVa5R/miaLIKFYsMqTZufYx0Ejd8pF6VeITXIIG4mALU50CGO/Q9ihMiJQWjok/jWkB0Qn6pqomcoJ5qdCnBHSh3XF2y6MaTutgICbaGRHUxGk1eynFE3sCOM6RfH6LIKr9Ql9Co/5wi76KF9Y0s6zbBsk/WfDdLEjG52Js4GWqdJUb6SOlNB5Mhg3VxMb9Uzf/w/MYq/+EjC2RwjAQIz4D78LIUhDEU8vYzBk8Jkd9J72JIk/ldzUsNk+r3Az/hQGjBHOGbtL0RO/V6yCET0p3aofJlXKO/EJ7yT4WrI1ALBKObzBnHb8sgv6shk+S0HBFstahY/qCRBnhC1+RqdDX1F4PL0AHuqX3ckNviCoCBvjBc7wtOAa5Zz29RYt0=
  app: img-resizer-srv
