language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python test.py
deploy:
  provider: heroku
  api_key: hjcSvviMNFd5X3h9ZYFlnksFG3mOAtDr6rPLaIAdyATDrE1K4DaFfz8X3RGGhQBhyqU4r8LpQiLVi8X5qpYnBKBmDVv5RLzsIiPYgrpfoXDxLb23yCs7mcE90INKyIV+5OnPNe1rSj+qVZJT5Qu3cHd5xZbbMwpsTLBro2v9QqcIpf645lJXT7ph3ZtcY59SZ030/OrpB4QTyDYbd5YCy+J7fPF2kUADtA8nhT/MJSTNoDa2f9965N96a0dEju5NfTE3dBk539TqIHrVZhXoWwXQp+BiSgWbnGqqDE8GuwRygQ5o8K4pW5Ziq0gZaPYpCuP5//RYAf0m9RKPVOb4lm7JQiO2z8knCS8zBVzyvpGTRaLGCn37klU74qILPd1KPnPQyiSuaZQNKB0/uYjqB3QyyMtcyumOTiG7j+AnB3eY0n2kiyq+qAlFKgNPh8bnKIuHkjfA7Upkc15UtkWlLuICJSGzMJHQ2RhVj34D8fbsZJO2uqCUpwwXMa7mDaszMbUN4niD5kfoF5JbJzuNa7NTQGlrzO9B6j6ZTFgv/ijyio77EPZYOp2nZl+Vat6Ljl4+pCmWOloaQ4GMKr9+uGUO47ywNiJRkvNCF+Hxz5Xez9l4hqtx9iGI7iswQW3sO9X9L3qGQt9yggwIFaHcPxWan/l5D4gcIi7XuRYWrjw=
  app: img-resizer-srv
